default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
Modern-contrast: styles/modern-contrast.scss
Modern-dark: styles/modern-dark.scss
Modern-light: styles/modern-light.scss